name: API Acceptance Tests

# Only run manually or on a schedule to avoid unexpected API costs
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Run once a week on Monday at 5 AM UTC
    - cron: '0 5 * * 1'

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    # Optional: Use environment for better secret management
    # environment: acceptance-testing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run acceptance tests with coverage
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
      run: |
        python -m pytest tests/acceptance_tests.py -v --cov=src --cov-report=xml
    
    # Only upload artifacts if we actually have coverage data
    - name: Upload test results
      if: always() && hashFiles('.coverage') != ''
      uses: actions/upload-artifact@v4
      with:
        name: acceptance-test-results
        path: |
          .coverage
          coverage.xml
        retention-days: 14  # How long to keep the artifacts
        
    # Provide a status even if test coverage wasn't generated
    - name: Report acceptance test status
      if: always()
      run: |
        echo "Acceptance tests completed. Check the logs for results."