name: API Acceptance Tests

# Only run manually or on a schedule to avoid unexpected API costs
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # Run once a week on Monday at 5 AM UTC
    - cron: '0 5 * * 1'

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run acceptance tests
      env:
        FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
      run: |
        python -m pytest tests/acceptance_tests.py -v
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: acceptance-test-results
        path: |
          .coverage
          coverage.xml